stages:
  - build

variables:
  PROJECT_NAME: common-starter
  PROJECT_VERSION: 0.0.1-SNAPSHOT
  VERSION: $CI_BUILD_REF_NAME
  POST_ADDRESS: empty

build:
  stage: build
  script:
    - mvn -U clean deploy -Dmaven.test.skip=true
  except:
    - develop


