stages:
  - build
  - deploy

variables:
  PROJECT_NAME: manager
  PROJECT_VERSION: 1.0-SNAPSHOT
  VERSION: $CI_BUILD_REF_NAME
  POST_ADDRESS: empty
  REGISTRY_SERVER: 172.17.0.1:5000

build:
  stage: build
  script:
    - mvn clean compile -U
  except:
#    - donghang-dev
#    - /^release-.*$/
    - master
  tags:
    - ww2

deploy-master:
  stage: deploy
  only:
    - master
  script:
#    - mvn -N deploy
    - mvn -U clean deploy -Dmaven.test.skip=true
    - cd manager-web
    - BUILD_VERSION="v`date +%Y%m%d%H%M`"
#    - docker login -u admin -p 81620872@w 172.17.0.1:5000
    - docker build -t "${REGISTRY_SERVER}/manager-web:${BUILD_VERSION}-${VERSION}" .
    - docker push "${REGISTRY_SERVER}/manager-web:${BUILD_VERSION}-${VERSION}"
    - docker rmi "${REGISTRY_SERVER}/manager-web:${BUILD_VERSION}-${VERSION}"
    - mvn -U clean package -Dmaven.test.skip=true
  tags:
    - ww2

